services:
  rtsp-recorder:
    build: .
    ports:
      - "8217:8217"
    volumes:
      - ./recordings:/recordings
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      - RUNNING_IN_DOCKER=True
    env_file:
      - .env
